default_simple:
  fit_params:
    batch_size: 64
    epochs: 20
  build_params:
    optimizer: adam
    loss: mse
  look_back: 30
  type: simple # multivariate or simple
  _name: lstm

default_multivariate:
  fit_params:
    batch_size: 64
    epochs: 20
  build_params:
    optimizer: adam
    loss: mse
  look_back: 30
  type: multivariate # multivariate or simple
  _name: lstm