models:
  xgboost:
    loss: squarederror
    n_estimators: 1000
    learning_rate: 0.01
    epochs: 1

  lstm:
    optimizer: adam
    loss: mse
    batch_size: 64
    learning_rate: 0.01
    look_back: 30
    type: simple
    epochs: 1


  prophet:
    optimizer: adam
    loss: mse
    batch_size: 16
    epochs: 1
