models:
  arima:
    optimizer: adam
    loss: mse
    batch_size: 32
    epochs: 1

  lstm:
    optimizer: adam
    loss: mse
    batch_size: 64
    epochs: 1
    look_back: 30

  prophet:
    optimizer: adam
    loss: mse
    batch_size: 16
    epochs: 1

  rnn:
    optimizer: adam
    loss: mse
    batch_size: 16
    epochs: 1