models:
  xgboost:
    loss: squarederror
    learning_rate: 0.01
    max_depth: 6
    n_estimators: 10000

  lstm:
    optimizer: adam
    loss: mse
    batch_size: 64
    look_back: 30
    type: simple # multivariate or simple
    epochs: 20

  prophet:
    
