default:
  fit_params:
    early_stopping_rounds: 100
    eval_metric: rmse
    verbose: 100
  build_params:
    loss: squarederror
    learning_rate: 0.01
    max_depth: 6
    n_estimators: 10000
  _name: xgboost
  save_path: models/xgboost