default:
  fit_params:
    verbose: True
  build_params:
    loss: squarederror
    learning_rate: 0.01
    max_depth: 6
    n_estimators: 10000
    eval_metric: rmse
    early_stopping_rounds: 100
  _name: xgboost

default_scaled:
  fit_params:
    verbose: True
  build_params:
    loss: squarederror
    learning_rate: 0.01
    max_depth: 6
    n_estimators: 10000
    eval_metric: rmse
    early_stopping_rounds: 100
  _name: xgboost
  scaled: True

default_max_depth_12:
  fit_params:
    verbose: True
  build_params:
    loss: squarederror
    learning_rate: 0.01
    max_depth: 12
    n_estimators: 10000
    eval_metric: rmse
    early_stopping_rounds: 100
  _name: xgboost

best_params:
  fit_params:
    verbose: True
  build_params:
    loss: squarederror
    learning_rate: 0.1
    max_depth: 3
    n_estimators: 2000
    eval_metric: rmse
    colsample_bytree: 0.9
    gamma: 0.3
    reg_alpha: 1e-05
    reg_lambda: 1
  _name: xgboost

best_params_earthquake:
  fit_params:
    verbose: True
  build_params:
    loss: squarederror
    learning_rate: 0.01
    max_depth: 3
    n_estimators: 2000
    eval_metric: rmse
    colsample_bytree: 0.7
    gamma: 0.1
    reg_alpha: 0.01
    reg_lambda: 0.01
  _name: xgboost
  earthquake: True