validation:
  models:
    xgboost:
      - xgboost default - 2024-01-22 12:11:45
    lstm:
      #- lstm default_multivariate - 2024-01-22 13:06:43
      - lstm default_simple - 2024-01-22 11:27:38
    prophet:
      - prophet default - 2024-01-22 11:22:01